name: hospital_project_22
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  shared_preferences: ^2.1.2
  flutter_native_splash: ^2.3.1
  image_picker: ^0.8.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/
     - assets/svge/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


# Generated by Spider
# For more info on configuration, visit https://birjuvachhani.github.io/spider/grouping/
spider:
  # Generates unit tests to verify that the assets exists in assets directory
  generate_tests: true
  # Use this to remove vcs noise created by the `generated` comments in dart code
  no_comments: true
  # Exports all the generated file as the one library
  export: true
  # This allows you to import all the generated references with 1 single import!
  use_part_of: true
  # Generates a variable that contains a list of all asset values.
  use_references_list: false
  # Generates files with given ignore rules for file.
  # ignored_rules:
  #   - public_member_api_docs
  # Generates dart font family references for fonts specified in pubspec.yaml
  # fonts: true
  # -------- OR --------
  # fonts:
  #   class_name: MyFonts
  #   file_name: my_fonts
  # Location where all the generated references will be stored
  package: resources
  groups:
    - path: assets/images
      class_name: Images
      types: [ .png, .jpg, .jpeg, .webp, .webm, .bmp ]